### ISSUE TITLE
How is this different from TemplateController?

### ISSUE THREAD

**Issue by orefalo** [comerc/meteor-template2#1]

**Comment by comerc** [comment]
[Key features](https://github.com/comerc/meteor-template2#key-features)!

**Comment by orefalo** [comment]
Thank you.

Please consider that if I ask, others may be confused as well. I think you should move the section right below, a fork of TemplateController.

Question:Isn't TemplateController already MVVM friendly? there is a demo at hte end of the page with 2way bindings.

**Comment by orefalo** [comment]
think I am starting to get it ;-)

**Comment by comerc** [comment]
Added Table of Contents.
Thanks you!

**Comment by comerc** [comment]
https://github.com/meteor-space/template-controller/issues/35

**Comment by orefalo** [comment]
great - my two cents... you should add it to the documentation. It's the first thing I was looking for when I found your project. sincerely
